name: build and upload to docker
on: [push,workflow_dispatch]
jobs:
  version-test:
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
          os: [windows-latest,ubuntu-latest]
          node: [15,16]
    steps:
      - name: pull the code
        uses: actions/checkout@v3
      - name: download node
        uses: actions/setup@v3
        with:
         node-version: ${{ matrix.node }}
      - name: version
        run: node -v
 
